### PR TITLE
v1.0.10

### PR DESCRIPTION
**Pull request by ThummeTo**
DiffEqCallbacks update

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Why is this?

**Comment by ThummeTo** [comment]
you mean the cap?

**Comment by ChrisRackauckas** [comment]
yes

**Comment by ThummeTo** [comment]
there was an issue in the past (but don't know which one exactly to be honest), but I can check for if this is still the case or if we can remove it.

**Comment by ChrisRackauckas** [comment]
Okay thanks and if you hit anything here I can help point out what to do, just noticed it deep in the stack and thought it's worth fixing.

**Comment by ThummeTo** [comment]
I just found that I already removed the cap in the feature branch #47 :-)

**Pull request merged**
